contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #gpseq channel"
    url: https://nfcore.slack.com/channels/gpseq
    about: Discussion about the nf-core/gpseq pipeline
